"""Add StoryDesign and Update User

Revision ID: d7cb0114c5dd
Revises: 3da6066204da
Create Date: 2025-12-16 16:59:38.491485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cb0114c5dd'
down_revision: Union[str, Sequence[str], None] = '3da6066204da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_designs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_story_designs_user_id'), 'story_designs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_designs_user_id'), table_name='story_designs')
    op.drop_column('story_designs', 'created_at')
    # ### end Alembic commands ###
